name: clippy

on:
  push:
  pull_request:
    branches:
      - master
  schedule:
    # At 06:00am every Saturday (for new versions of clippy)
    - cron:  '0 6 * * 6'

jobs:
  run_clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features