name: test

on:
  push:
  pull_request:
    branches:
      - master
  schedule:
    # At 06:00am every Saturday (for new versions of rustc)
    - cron:  '0 6 * * 6'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Cargo dependencies security audit
      uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Test
      run: cargo test --verbose